redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\samiu\\OneDrive\\Desktop\\Feature_Desk_G\\netlify\\functions"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "C:\\Users\\samiu\\OneDrive\\Desktop\\Feature_Desk_G\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\samiu\\OneDrive\\Desktop\\Feature_Desk_G"
command = "npm run build"
functions = "C:\\Users\\samiu\\OneDrive\\Desktop\\Feature_Desk_G\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*.js"

[headers.values]
Content-Type = "application/javascript; charset=utf-8"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.css"

[headers.values]
Content-Type = "text/css; charset=utf-8"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.woff2"

[headers.values]
Content-Type = "font/woff2"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.css"

[headers.values]
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/mongodb"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]